--- #YAML:1.0
name:                Parse-Eyapp
version:             1.088
abstract:            Extensions for Parse::Yapp
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Data::Dumper:                  1.0
    List::MoreUtils:               0
    List::Util:                    1.0
    Pod::Usage:                    1.0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casiano Rodriguez-Leon <casiano@ull.es>
